---
# This variables file is used by the playbooks in the local group.

# Flux Bootstrap Configuration
github_token: "{{ flux_github_token }}"
github_username: gawbul
gitops_repository: gawbul-gitops
gitops_branch: flux-bootstrap
gitops_path: clusters/eniac
